### ISSUE TITLE
Vectorisation of regularize() function in special_orthogonal_group.py

### ISSUE THREAD

**Issue by farrell236** [ninamiolane/geomstats#33]
If the input array for regularise in class SpecialOrthogonalGroup class is of Nx3, where N is the number of SO(3) vectors to regularise, I don't think the regularisation function is correct if N > 1 as np.linalg.norm(rot_vec) calculates the norm of the entire Nx3 matrix. 

Should the code be as follows?

```
rot_vec = vectorization.expand_dims(rot_vec, to_ndim=2)
assert self.belongs(rot_vec)

angle = np.linalg.norm(rot_vec,axis=1)
regularized_rot_vec = rot_vec

k = np.floor(angle / (2 * np.pi) + .5)
fact = (1. - 2. * np.pi * k / angle)

fact[angle == 0] = 1

regularized_rot_vec = (rot_vec.T * fact).T

assert regularized_rot_vec.ndim == 2
return regularized_rot_vec

```

**Comment by ninamiolane** [comment]
Thanks! It is fixed now.
